package io.zak.delivery.data.entities;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity(tableName = "vehicle_stocks")
public class VehicleStock {
    @PrimaryKey(autoGenerate = true)
    public int vehicleStockId;      // autogenerated id
    public int fkVehicleId;         // vehicle id currently used by the delivery
    public int fkProductId;         // product id (products must be synchronized with the inventory app)
    public int fkWarehouseStockId;  // warehouse the stock's belongs/stored
    public int quantity;            // actual remaining stocks
    public int orderedQuantity;     // ordered stocks
    public double sellingPrice;     // may differ from the product's actual price
    public double totalAmount;      // quantity * sellingPrice
    public long dateOrdered;        // date transferred from warehouse to vehicle
}
